
/**
 * @roxi/routify 2.18.7
 * File generated Fri Jun 10 2022 22:55:21 GMT+0200 (Central European Summer Time)
 */

export const __version = "2.18.7"
export const __timestamp = "2022-06-10T20:55:21.906Z"

//buildRoutes
import { buildClientTree } from "@roxi/routify/runtime/buildRoutes"

//imports


//options
export const options = {}

//tree
export const _tree = {
  "name": "_layout",
  "filepath": "/_layout.svelte",
  "root": true,
  "ownMeta": {},
  "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/_layout.svelte",
  "children": [
    {
      "isFile": true,
      "isDir": false,
      "file": "_fallback.svelte",
      "filepath": "/_fallback.svelte",
      "name": "_fallback",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/_fallback.svelte",
      "importPath": "../src/routes/_fallback.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": true,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/_fallback",
      "id": "__fallback",
      "component": () => import('../src/routes/_fallback.svelte').then(m => m.default)
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "components",
      "filepath": "/components",
      "name": "components",
      "ext": "",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "Accordion.svelte",
          "filepath": "/components/Accordion.svelte",
          "name": "Accordion",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Accordion.svelte",
          "importPath": "../src/routes/components/Accordion.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Accordion",
          "id": "_components_Accordion",
          "component": () => import('../src/routes/components/Accordion.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Animations.svelte",
          "filepath": "/components/Animations.svelte",
          "name": "Animations",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Animations.svelte",
          "importPath": "../src/routes/components/Animations.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Animations",
          "id": "_components_Animations",
          "component": () => import('../src/routes/components/Animations.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Avatars.svelte",
          "filepath": "/components/Avatars.svelte",
          "name": "Avatars",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Avatars.svelte",
          "importPath": "../src/routes/components/Avatars.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Avatars",
          "id": "_components_Avatars",
          "component": () => import('../src/routes/components/Avatars.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Badge.svelte",
          "filepath": "/components/Badge.svelte",
          "name": "Badge",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Badge.svelte",
          "importPath": "../src/routes/components/Badge.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Badge",
          "id": "_components_Badge",
          "component": () => import('../src/routes/components/Badge.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Breadcrumb.svelte",
          "filepath": "/components/Breadcrumb.svelte",
          "name": "Breadcrumb",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Breadcrumb.svelte",
          "importPath": "../src/routes/components/Breadcrumb.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Breadcrumb",
          "id": "_components_Breadcrumb",
          "component": () => import('../src/routes/components/Breadcrumb.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Button.svelte",
          "filepath": "/components/Button.svelte",
          "name": "Button",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Button.svelte",
          "importPath": "../src/routes/components/Button.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Button",
          "id": "_components_Button",
          "component": () => import('../src/routes/components/Button.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Card.svelte",
          "filepath": "/components/Card.svelte",
          "name": "Card",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Card.svelte",
          "importPath": "../src/routes/components/Card.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Card",
          "id": "_components_Card",
          "component": () => import('../src/routes/components/Card.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Checkbox.svelte",
          "filepath": "/components/Checkbox.svelte",
          "name": "Checkbox",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Checkbox.svelte",
          "importPath": "../src/routes/components/Checkbox.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Checkbox",
          "id": "_components_Checkbox",
          "component": () => import('../src/routes/components/Checkbox.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Chip.svelte",
          "filepath": "/components/Chip.svelte",
          "name": "Chip",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Chip.svelte",
          "importPath": "../src/routes/components/Chip.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Chip",
          "id": "_components_Chip",
          "component": () => import('../src/routes/components/Chip.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Controllers.svelte",
          "filepath": "/components/Controllers.svelte",
          "name": "Controllers",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Controllers.svelte",
          "importPath": "../src/routes/components/Controllers.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Controllers",
          "id": "_components_Controllers",
          "component": () => import('../src/routes/components/Controllers.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Datetime.svelte",
          "filepath": "/components/Datetime.svelte",
          "name": "Datetime",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Datetime.svelte",
          "importPath": "../src/routes/components/Datetime.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Datetime",
          "id": "_components_Datetime",
          "component": () => import('../src/routes/components/Datetime.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Fab.svelte",
          "filepath": "/components/Fab.svelte",
          "name": "Fab",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Fab.svelte",
          "importPath": "../src/routes/components/Fab.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Fab",
          "id": "_components_Fab",
          "component": () => import('../src/routes/components/Fab.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Gesture.svelte",
          "filepath": "/components/Gesture.svelte",
          "name": "Gesture",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Gesture.svelte",
          "importPath": "../src/routes/components/Gesture.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Gesture",
          "id": "_components_Gesture",
          "component": () => import('../src/routes/components/Gesture.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Grid.svelte",
          "filepath": "/components/Grid.svelte",
          "name": "Grid",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Grid.svelte",
          "importPath": "../src/routes/components/Grid.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Grid",
          "id": "_components_Grid",
          "component": () => import('../src/routes/components/Grid.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Icon.svelte",
          "filepath": "/components/Icon.svelte",
          "name": "Icon",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Icon.svelte",
          "importPath": "../src/routes/components/Icon.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Icon",
          "id": "_components_Icon",
          "component": () => import('../src/routes/components/Icon.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Infinitescroll.svelte",
          "filepath": "/components/Infinitescroll.svelte",
          "name": "Infinitescroll",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Infinitescroll.svelte",
          "importPath": "../src/routes/components/Infinitescroll.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Infinitescroll",
          "id": "_components_Infinitescroll",
          "component": () => import('../src/routes/components/Infinitescroll.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Inputs.svelte",
          "filepath": "/components/Inputs.svelte",
          "name": "Inputs",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Inputs.svelte",
          "importPath": "../src/routes/components/Inputs.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Inputs",
          "id": "_components_Inputs",
          "component": () => import('../src/routes/components/Inputs.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Item.svelte",
          "filepath": "/components/Item.svelte",
          "name": "Item",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Item.svelte",
          "importPath": "../src/routes/components/Item.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Item",
          "id": "_components_Item",
          "component": () => import('../src/routes/components/Item.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "List.svelte",
          "filepath": "/components/List.svelte",
          "name": "List",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/List.svelte",
          "importPath": "../src/routes/components/List.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/List",
          "id": "_components_List",
          "component": () => import('../src/routes/components/List.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Note.svelte",
          "filepath": "/components/Note.svelte",
          "name": "Note",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Note.svelte",
          "importPath": "../src/routes/components/Note.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Note",
          "id": "_components_Note",
          "component": () => import('../src/routes/components/Note.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Page.svelte",
          "filepath": "/components/Page.svelte",
          "name": "Page",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Page.svelte",
          "importPath": "../src/routes/components/Page.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Page",
          "id": "_components_Page",
          "component": () => import('../src/routes/components/Page.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Platform.svelte",
          "filepath": "/components/Platform.svelte",
          "name": "Platform",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Platform.svelte",
          "importPath": "../src/routes/components/Platform.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Platform",
          "id": "_components_Platform",
          "component": () => import('../src/routes/components/Platform.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "ProgressBar.svelte",
          "filepath": "/components/ProgressBar.svelte",
          "name": "ProgressBar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/ProgressBar.svelte",
          "importPath": "../src/routes/components/ProgressBar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/ProgressBar",
          "id": "_components_ProgressBar",
          "component": () => import('../src/routes/components/ProgressBar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Radio.svelte",
          "filepath": "/components/Radio.svelte",
          "name": "Radio",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Radio.svelte",
          "importPath": "../src/routes/components/Radio.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Radio",
          "id": "_components_Radio",
          "component": () => import('../src/routes/components/Radio.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Range.svelte",
          "filepath": "/components/Range.svelte",
          "name": "Range",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Range.svelte",
          "importPath": "../src/routes/components/Range.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Range",
          "id": "_components_Range",
          "component": () => import('../src/routes/components/Range.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Refresher.svelte",
          "filepath": "/components/Refresher.svelte",
          "name": "Refresher",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Refresher.svelte",
          "importPath": "../src/routes/components/Refresher.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Refresher",
          "id": "_components_Refresher",
          "component": () => import('../src/routes/components/Refresher.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Reorder.svelte",
          "filepath": "/components/Reorder.svelte",
          "name": "Reorder",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Reorder.svelte",
          "importPath": "../src/routes/components/Reorder.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Reorder",
          "id": "_components_Reorder",
          "component": () => import('../src/routes/components/Reorder.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Searchbar.svelte",
          "filepath": "/components/Searchbar.svelte",
          "name": "Searchbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Searchbar.svelte",
          "importPath": "../src/routes/components/Searchbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Searchbar",
          "id": "_components_Searchbar",
          "component": () => import('../src/routes/components/Searchbar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Segment.svelte",
          "filepath": "/components/Segment.svelte",
          "name": "Segment",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Segment.svelte",
          "importPath": "../src/routes/components/Segment.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Segment",
          "id": "_components_Segment",
          "component": () => import('../src/routes/components/Segment.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Select.svelte",
          "filepath": "/components/Select.svelte",
          "name": "Select",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Select.svelte",
          "importPath": "../src/routes/components/Select.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Select",
          "id": "_components_Select",
          "component": () => import('../src/routes/components/Select.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Skeleton.svelte",
          "filepath": "/components/Skeleton.svelte",
          "name": "Skeleton",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Skeleton.svelte",
          "importPath": "../src/routes/components/Skeleton.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Skeleton",
          "id": "_components_Skeleton",
          "component": () => import('../src/routes/components/Skeleton.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Slides.svelte",
          "filepath": "/components/Slides.svelte",
          "name": "Slides",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Slides.svelte",
          "importPath": "../src/routes/components/Slides.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Slides",
          "id": "_components_Slides",
          "component": () => import('../src/routes/components/Slides.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Spinner.svelte",
          "filepath": "/components/Spinner.svelte",
          "name": "Spinner",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Spinner.svelte",
          "importPath": "../src/routes/components/Spinner.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Spinner",
          "id": "_components_Spinner",
          "component": () => import('../src/routes/components/Spinner.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Splash.svelte",
          "filepath": "/components/Splash.svelte",
          "name": "Splash",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Splash.svelte",
          "importPath": "../src/routes/components/Splash.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Splash",
          "id": "_components_Splash",
          "component": () => import('../src/routes/components/Splash.svelte').then(m => m.default)
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "tabs",
          "filepath": "/components/tabs",
          "name": "tabs",
          "ext": "",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/tabs",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "[tab].svelte",
              "filepath": "/components/tabs/[tab].svelte",
              "name": "[tab]",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/tabs/[tab].svelte",
              "importPath": "../src/routes/components/tabs/[tab].svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "recursive": true,
                "preload": false,
                "prerender": true
              },
              "path": "/components/tabs/:tab",
              "id": "_components_tabs__tab",
              "component": () => import('../src/routes/components/tabs/[tab].svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/tabs"
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Text.svelte",
          "filepath": "/components/Text.svelte",
          "name": "Text",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Text.svelte",
          "importPath": "../src/routes/components/Text.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Text",
          "id": "_components_Text",
          "component": () => import('../src/routes/components/Text.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Thumbnails.svelte",
          "filepath": "/components/Thumbnails.svelte",
          "name": "Thumbnails",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Thumbnails.svelte",
          "importPath": "../src/routes/components/Thumbnails.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Thumbnails",
          "id": "_components_Thumbnails",
          "component": () => import('../src/routes/components/Thumbnails.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toggle.svelte",
          "filepath": "/components/Toggle.svelte",
          "name": "Toggle",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Toggle.svelte",
          "importPath": "../src/routes/components/Toggle.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Toggle",
          "id": "_components_Toggle",
          "component": () => import('../src/routes/components/Toggle.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toolbar.svelte",
          "filepath": "/components/Toolbar.svelte",
          "name": "Toolbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/components/Toolbar.svelte",
          "importPath": "../src/routes/components/Toolbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Toolbar",
          "id": "_components_Toolbar",
          "component": () => import('../src/routes/components/Toolbar.svelte').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/components"
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "index.svelte",
      "filepath": "/index.svelte",
      "name": "index",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/routes/index.svelte",
      "importPath": "../src/routes/index.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": true,
      "isFallback": false,
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/index",
      "id": "_index",
      "component": () => import('../src/routes/index.svelte').then(m => m.default)
    }
  ],
  "isLayout": true,
  "isReset": false,
  "isIndex": false,
  "isFallback": false,
  "isPage": false,
  "isFile": true,
  "file": "_layout.svelte",
  "ext": "svelte",
  "badExt": false,
  "importPath": "../src/routes/_layout.svelte",
  "meta": {
    "recursive": true,
    "preload": false,
    "prerender": true
  },
  "path": "/",
  "id": "__layout",
  "component": () => import('../src/routes/_layout.svelte').then(m => m.default)
}


export const {tree, routes} = buildClientTree(_tree)

