
/**
 * @roxi/routify 2.18.7
 * File generated Sat Jun 04 2022 13:42:59 GMT+0200 (Central European Summer Time)
 */

export const __version = "2.18.7"
export const __timestamp = "2022-06-04T11:42:59.411Z"

//buildRoutes
import { buildClientTree } from "@roxi/routify/runtime/buildRoutes"

//imports


//options
export const options = {}

//tree
export const _tree = {
  "name": "_layout",
  "filepath": "/_layout.svelte",
  "root": true,
  "ownMeta": {},
  "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/_layout.svelte",
  "children": [
    {
      "isFile": false,
      "isDir": true,
      "file": "components",
      "filepath": "/components",
      "name": "components",
      "ext": "",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "Avatars.svelte",
          "filepath": "/components/Avatars.svelte",
          "name": "Avatars",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Avatars.svelte",
          "importPath": "../src/pages/components/Avatars.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Avatars",
          "id": "_components_Avatars",
          "component": () => import('../src/pages/components/Avatars.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Badge.svelte",
          "filepath": "/components/Badge.svelte",
          "name": "Badge",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Badge.svelte",
          "importPath": "../src/pages/components/Badge.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Badge",
          "id": "_components_Badge",
          "component": () => import('../src/pages/components/Badge.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Button.svelte",
          "filepath": "/components/Button.svelte",
          "name": "Button",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Button.svelte",
          "importPath": "../src/pages/components/Button.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Button",
          "id": "_components_Button",
          "component": () => import('../src/pages/components/Button.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Card.svelte",
          "filepath": "/components/Card.svelte",
          "name": "Card",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Card.svelte",
          "importPath": "../src/pages/components/Card.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Card",
          "id": "_components_Card",
          "component": () => import('../src/pages/components/Card.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Checkbox.svelte",
          "filepath": "/components/Checkbox.svelte",
          "name": "Checkbox",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Checkbox.svelte",
          "importPath": "../src/pages/components/Checkbox.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Checkbox",
          "id": "_components_Checkbox",
          "component": () => import('../src/pages/components/Checkbox.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Chip.svelte",
          "filepath": "/components/Chip.svelte",
          "name": "Chip",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Chip.svelte",
          "importPath": "../src/pages/components/Chip.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Chip",
          "id": "_components_Chip",
          "component": () => import('../src/pages/components/Chip.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Controllers.svelte",
          "filepath": "/components/Controllers.svelte",
          "name": "Controllers",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Controllers.svelte",
          "importPath": "../src/pages/components/Controllers.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Controllers",
          "id": "_components_Controllers",
          "component": () => import('../src/pages/components/Controllers.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Datetime.svelte",
          "filepath": "/components/Datetime.svelte",
          "name": "Datetime",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Datetime.svelte",
          "importPath": "../src/pages/components/Datetime.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Datetime",
          "id": "_components_Datetime",
          "component": () => import('../src/pages/components/Datetime.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Fab.svelte",
          "filepath": "/components/Fab.svelte",
          "name": "Fab",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Fab.svelte",
          "importPath": "../src/pages/components/Fab.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Fab",
          "id": "_components_Fab",
          "component": () => import('../src/pages/components/Fab.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Games.svelte",
          "filepath": "/components/Games.svelte",
          "name": "Games",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Games.svelte",
          "importPath": "../src/pages/components/Games.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Games",
          "id": "_components_Games",
          "component": () => import('../src/pages/components/Games.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Grid.svelte",
          "filepath": "/components/Grid.svelte",
          "name": "Grid",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Grid.svelte",
          "importPath": "../src/pages/components/Grid.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Grid",
          "id": "_components_Grid",
          "component": () => import('../src/pages/components/Grid.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Icon.svelte",
          "filepath": "/components/Icon.svelte",
          "name": "Icon",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Icon.svelte",
          "importPath": "../src/pages/components/Icon.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Icon",
          "id": "_components_Icon",
          "component": () => import('../src/pages/components/Icon.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Infinitescroll.svelte",
          "filepath": "/components/Infinitescroll.svelte",
          "name": "Infinitescroll",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Infinitescroll.svelte",
          "importPath": "../src/pages/components/Infinitescroll.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Infinitescroll",
          "id": "_components_Infinitescroll",
          "component": () => import('../src/pages/components/Infinitescroll.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Inputs.svelte",
          "filepath": "/components/Inputs.svelte",
          "name": "Inputs",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Inputs.svelte",
          "importPath": "../src/pages/components/Inputs.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Inputs",
          "id": "_components_Inputs",
          "component": () => import('../src/pages/components/Inputs.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Item.svelte",
          "filepath": "/components/Item.svelte",
          "name": "Item",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Item.svelte",
          "importPath": "../src/pages/components/Item.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Item",
          "id": "_components_Item",
          "component": () => import('../src/pages/components/Item.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "List.svelte",
          "filepath": "/components/List.svelte",
          "name": "List",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/List.svelte",
          "importPath": "../src/pages/components/List.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/List",
          "id": "_components_List",
          "component": () => import('../src/pages/components/List.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "ModalExtra.svelte",
          "filepath": "/components/ModalExtra.svelte",
          "name": "ModalExtra",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/ModalExtra.svelte",
          "importPath": "../src/pages/components/ModalExtra.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/ModalExtra",
          "id": "_components_ModalExtra",
          "component": () => import('../src/pages/components/ModalExtra.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Music.svelte",
          "filepath": "/components/Music.svelte",
          "name": "Music",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Music.svelte",
          "importPath": "../src/pages/components/Music.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Music",
          "id": "_components_Music",
          "component": () => import('../src/pages/components/Music.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Nav.svelte",
          "filepath": "/components/Nav.svelte",
          "name": "Nav",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Nav.svelte",
          "importPath": "../src/pages/components/Nav.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Nav",
          "id": "_components_Nav",
          "component": () => import('../src/pages/components/Nav.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "NavDetail.svelte",
          "filepath": "/components/NavDetail.svelte",
          "name": "NavDetail",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/NavDetail.svelte",
          "importPath": "../src/pages/components/NavDetail.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/NavDetail",
          "id": "_components_NavDetail",
          "component": () => import('../src/pages/components/NavDetail.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "NavList.svelte",
          "filepath": "/components/NavList.svelte",
          "name": "NavList",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/NavList.svelte",
          "importPath": "../src/pages/components/NavList.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/NavList",
          "id": "_components_NavList",
          "component": () => import('../src/pages/components/NavList.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Note.svelte",
          "filepath": "/components/Note.svelte",
          "name": "Note",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Note.svelte",
          "importPath": "../src/pages/components/Note.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Note",
          "id": "_components_Note",
          "component": () => import('../src/pages/components/Note.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "PopoverExtra.svelte",
          "filepath": "/components/PopoverExtra.svelte",
          "name": "PopoverExtra",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/PopoverExtra.svelte",
          "importPath": "../src/pages/components/PopoverExtra.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/PopoverExtra",
          "id": "_components_PopoverExtra",
          "component": () => import('../src/pages/components/PopoverExtra.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "ProgressBar.svelte",
          "filepath": "/components/ProgressBar.svelte",
          "name": "ProgressBar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/ProgressBar.svelte",
          "importPath": "../src/pages/components/ProgressBar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/ProgressBar",
          "id": "_components_ProgressBar",
          "component": () => import('../src/pages/components/ProgressBar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Radio.svelte",
          "filepath": "/components/Radio.svelte",
          "name": "Radio",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Radio.svelte",
          "importPath": "../src/pages/components/Radio.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Radio",
          "id": "_components_Radio",
          "component": () => import('../src/pages/components/Radio.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Range.svelte",
          "filepath": "/components/Range.svelte",
          "name": "Range",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Range.svelte",
          "importPath": "../src/pages/components/Range.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Range",
          "id": "_components_Range",
          "component": () => import('../src/pages/components/Range.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Refresher.svelte",
          "filepath": "/components/Refresher.svelte",
          "name": "Refresher",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Refresher.svelte",
          "importPath": "../src/pages/components/Refresher.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Refresher",
          "id": "_components_Refresher",
          "component": () => import('../src/pages/components/Refresher.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Reorder.svelte",
          "filepath": "/components/Reorder.svelte",
          "name": "Reorder",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Reorder.svelte",
          "importPath": "../src/pages/components/Reorder.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Reorder",
          "id": "_components_Reorder",
          "component": () => import('../src/pages/components/Reorder.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Searchbar.svelte",
          "filepath": "/components/Searchbar.svelte",
          "name": "Searchbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Searchbar.svelte",
          "importPath": "../src/pages/components/Searchbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Searchbar",
          "id": "_components_Searchbar",
          "component": () => import('../src/pages/components/Searchbar.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Segment.svelte",
          "filepath": "/components/Segment.svelte",
          "name": "Segment",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Segment.svelte",
          "importPath": "../src/pages/components/Segment.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Segment",
          "id": "_components_Segment",
          "component": () => import('../src/pages/components/Segment.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Select.svelte",
          "filepath": "/components/Select.svelte",
          "name": "Select",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Select.svelte",
          "importPath": "../src/pages/components/Select.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Select",
          "id": "_components_Select",
          "component": () => import('../src/pages/components/Select.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Skeleton.svelte",
          "filepath": "/components/Skeleton.svelte",
          "name": "Skeleton",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Skeleton.svelte",
          "importPath": "../src/pages/components/Skeleton.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Skeleton",
          "id": "_components_Skeleton",
          "component": () => import('../src/pages/components/Skeleton.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Slides.svelte",
          "filepath": "/components/Slides.svelte",
          "name": "Slides",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Slides.svelte",
          "importPath": "../src/pages/components/Slides.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Slides",
          "id": "_components_Slides",
          "component": () => import('../src/pages/components/Slides.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Spinner.svelte",
          "filepath": "/components/Spinner.svelte",
          "name": "Spinner",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Spinner.svelte",
          "importPath": "../src/pages/components/Spinner.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Spinner",
          "id": "_components_Spinner",
          "component": () => import('../src/pages/components/Spinner.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Text.svelte",
          "filepath": "/components/Text.svelte",
          "name": "Text",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Text.svelte",
          "importPath": "../src/pages/components/Text.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Text",
          "id": "_components_Text",
          "component": () => import('../src/pages/components/Text.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Thumbnails.svelte",
          "filepath": "/components/Thumbnails.svelte",
          "name": "Thumbnails",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Thumbnails.svelte",
          "importPath": "../src/pages/components/Thumbnails.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Thumbnails",
          "id": "_components_Thumbnails",
          "component": () => import('../src/pages/components/Thumbnails.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toggle.svelte",
          "filepath": "/components/Toggle.svelte",
          "name": "Toggle",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Toggle.svelte",
          "importPath": "../src/pages/components/Toggle.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Toggle",
          "id": "_components_Toggle",
          "component": () => import('../src/pages/components/Toggle.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Toolbar.svelte",
          "filepath": "/components/Toolbar.svelte",
          "name": "Toolbar",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/components/Toolbar.svelte",
          "importPath": "../src/pages/components/Toolbar.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "recursive": true,
            "preload": false,
            "prerender": true
          },
          "path": "/components/Toolbar",
          "id": "_components_Toolbar",
          "component": () => import('../src/pages/components/Toolbar.svelte').then(m => m.default)
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/components"
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "index.svelte",
      "filepath": "/index.svelte",
      "name": "index",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "C:/Data/src/svelte-ionic-app/src/pages/index.svelte",
      "importPath": "../src/pages/index.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": true,
      "isFallback": false,
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "recursive": true,
        "preload": false,
        "prerender": true
      },
      "path": "/index",
      "id": "_index",
      "component": () => import('../src/pages/index.svelte').then(m => m.default)
    }
  ],
  "isLayout": true,
  "isReset": false,
  "isIndex": false,
  "isFallback": false,
  "isPage": false,
  "isFile": true,
  "file": "_layout.svelte",
  "ext": "svelte",
  "badExt": false,
  "importPath": "../src/pages/_layout.svelte",
  "meta": {
    "recursive": true,
    "preload": false,
    "prerender": true
  },
  "path": "/",
  "id": "__layout",
  "component": () => import('../src/pages/_layout.svelte').then(m => m.default)
}


export const {tree, routes} = buildClientTree(_tree)

